services:
  mysql:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=leo_vidros'
      - 'MYSQL_PASSWORD=leo_vidros_pass'
      - 'MYSQL_ROOT_PASSWORD=root123'
      - 'MYSQL_USER=leo_vidros'
    ports:
      - '3307:3306'

#  rabbitmq:
#    image: 'rabbitmq:3-management'
#    container_name: rabbitmq-leovidros
#    environment:
#      - 'RABBITMQ_DEFAULT_USER=leo_vidros'
#      - 'RABBITMQ_DEFAULT_PASS=leo_vidros_pass'
#    ports:
#      - '5672:5672'
#      - '15672:15672'
